### ISSUE TITLE
Add Dark Mode Support

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/year-in-progress#1]
The current progress bar is designed for light themes. It would be great to have an option that automatically switches to dark mode based on the user’s system preferences. The progress bar's background and text colors should adjust accordingly.

**Comment by parthib2004** [comment]
I can do it! Can you please assign this to me?

**Comment by parthib2004** [comment]
Hello, as the issue has been fixed, can you please close this issue?
