### ISSUE TITLE
Can I add contributors in readme file section?

### ISSUE THREAD

**Issue by saikatsardar01** [DhanushNehru/year-in-progress#29]
Can I add contributors in readme file section?

like this :-
![Screenshot 2024-10-06 085829](https://github.com/user-attachments/assets/ecf1b034-5a9b-4114-abee-8b360fb321cc)

**Comment by DhanushNehru** [comment]
Sure @saikatsardar01

**Comment by saikatsardar01** [comment]
@DhanushNehru Please assign it to me
